FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
COPY ../data ./data
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/hexakadal-backend-1.0.0.jar app.jar
COPY --from=build /app/data ./data
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
